#!/usr/bin/env groovy

pipeline {
    agent any

    stages {
        stage('init environment') {
            environment {
                flavor='test'
            }

            sh 'printenv'
        }

        stage('Build') {
            steps {
                sh 'pwd'
                sh './gradlew clean jar'
                archiveArtifacts '**/build/libs/*.jar'
            }
        }

        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}